defmodule Arkea.Sim.TickTest do
  # credo:disable-for-this-file Credo.Check.Refactor.Nesting
  # `gen all do ... end` blocks and StreamData.bind compose by nesting;
  # the canonical StreamData pattern legitimately exceeds Credo's depth here.

  use ExUnit.Case, async: true
  use ExUnitProperties

  alias Arkea.Ecology.Lineage
  alias Arkea.Ecology.Phase
  alias Arkea.Genome
  alias Arkea.Genome.Domain
  alias Arkea.Genome.Gene
  alias Arkea.Sim.BiotopeState
  alias Arkea.Sim.Tick

  import Arkea.Generators, only: [biotope_state: 0]

  alias Arkea.Sim.Phenotype

  @moduletag :sim

  # ---------------------------------------------------------------------------
  # Property: non-negativity of abundances after one tick

  property "abundance is non-negative after one tick for any input" do
    check all(state <- biotope_state()) do
      {new_state, _events} = Tick.tick(state)

      for lineage <- new_state.lineages,
          {_phase, count} <- lineage.abundance_by_phase do
        assert count >= 0,
               "negative abundance #{count} found in lineage #{lineage.id}"
      end
    end
  end

  # ---------------------------------------------------------------------------
  # Property: dilution-only monotonicity (zero-kcat genome → delta = 0)
  #
  # Phase 3: step_expression now derives growth_delta_by_lineage from the
  # genome. To test dilution-only monotonicity we use a genome that produces
  # delta = 0: a single catalytic_site domain with all-zero parameter_codons
  # gives kcat = 0.0, hence base_growth_rate = 0.0 and delta = 0.
  #
  # The biotope_state(growth_rate: 0) generator still seeds
  # growth_delta_by_lineage to 0, but step_expression overwrites it with
  # genome-derived values. By using a deterministically zero-kcat genome we
  # ensure the overwrite also produces delta = 0.

  property "abundance never increases when genome produces zero growth delta" do
    check all(state <- biotope_state_zero_delta()) do
      {new_state, _events} = Tick.tick(state)

      for old_lineage <- state.lineages do
        new_lineage =
          Enum.find(new_state.lineages, fn l -> l.id == old_lineage.id end)

        for {phase_name, old_count} <- old_lineage.abundance_by_phase do
          new_count = Map.get(new_lineage.abundance_by_phase, phase_name, 0)

          assert new_count <= old_count,
                 "abundance increased from #{old_count} to #{new_count} in " <>
                   "phase #{phase_name} of lineage #{old_lineage.id} with zero-growth genome"
        end
      end
    end
  end

  # ---------------------------------------------------------------------------
  # Property: tick is deterministic (pure function)
  #
  # Phase 4 note: `step_cell_events` may produce new child lineages whose UUIDs
  # are generated by `Ecto.UUID.generate/0` (backed by `:crypto.strong_rand_bytes`).
  # UUID generation is intentionally non-deterministic — lineage identity is a
  # global unique handle, not a derived value. Therefore the determinism property
  # is tested on states where no fission occurs: all lineage abundances are 0,
  # so `mutation_probability(0, _) = 0.0` and no children are spawned.

  property "tick is deterministic: same zero-abundance state produces same result" do
    check all(state <- biotope_state_zero_abundance()) do
      {result_a, events_a} = Tick.tick(state)
      {result_b, events_b} = Tick.tick(state)

      assert result_a == result_b,
             "tick returned different new states for the same zero-abundance input"

      assert events_a == events_b,
             "tick returned different events for the same zero-abundance input"
    end
  end

  # ---------------------------------------------------------------------------
  # Property: tick_count increments by exactly 1

  property "tick_count increments by 1 on every tick" do
    check all(state <- biotope_state()) do
      {new_state, _events} = Tick.tick(state)
      assert new_state.tick_count == state.tick_count + 1
    end
  end

  # ---------------------------------------------------------------------------
  # Property: events list is always a list (type contract)

  property "derive_events always returns a list" do
    check all(state <- biotope_state()) do
      {_new_state, events} = Tick.tick(state)
      assert is_list(events)
    end
  end

  # ---------------------------------------------------------------------------
  # Property: steps are composable and the full pipeline equals sequential steps
  #
  # Phase 4 note: `step_cell_events` generates new lineage UUIDs when fission
  # occurs (via `Lineage.new_child` → `Ecto.UUID.generate`). Two separate
  # invocations of `step_cell_events` on the same state will produce children
  # with different UUIDs. Therefore composability is verified on zero-abundance
  # states where no fission is triggered.

  property "step_cell_events followed by step_environment equals tick sub-pipeline (zero abundance)" do
    check all(state <- biotope_state_zero_abundance()) do
      # Apply steps manually in the same order as tick/1
      manual =
        state
        |> Tick.step_metabolism()
        |> Tick.step_expression()
        |> Tick.step_cell_events()
        |> Tick.step_hgt()
        |> Tick.step_environment()
        |> Tick.step_pruning()

      {ticked, _events} = Tick.tick(state)

      # tick/1 also increments tick_count, so we compare only the biological state
      assert manual.lineages == ticked.lineages,
             "manual pipeline and tick/1 disagree on lineages"

      assert manual.phases == ticked.phases,
             "manual pipeline and tick/1 disagree on phases"
    end
  end

  # ---------------------------------------------------------------------------
  # Unit: system reaches a stable fixed point (not necessarily the initial value)

  test "population converges to a stable fixed point after many ticks" do
    # With integer floor(), the discrete steady state differs from the
    # continuous equilibrium. For growth_delta d and dilution_rate r,
    # the fixed point a* satisfies: floor((a* + d) * (1 - r)) = a*
    # i.e. (a* + d)*(1-r) is in [a*, a*+1).
    # We simply verify that after sufficient ticks the population
    # stabilises (consecutive ticks do not change the count).

    phase_name = :surface
    dilution_rate = 0.1
    growth_delta = 10

    phases = [Phase.new(phase_name, dilution_rate: dilution_rate)]

    lineage =
      Lineage.new_founder(
        genome_fixture(),
        %{phase_name => 100},
        0
      )

    state =
      BiotopeState.new_from_opts(
        id: Arkea.UUID.v4(),
        archetype: :oligotrophic_lake,
        phases: phases,
        dilution_rate: dilution_rate,
        lineages: [lineage],
        growth_delta_by_lineage: %{lineage.id => %{phase_name => growth_delta}}
      )

    # Run until convergence (or max 200 ticks)
    {final_state, _} =
      Enum.reduce_while(1..200, {state, -1}, fn _, {acc, prev} ->
        {new_acc, _} = Tick.tick(acc)
        lineage_now = hd(new_acc.lineages)
        count = Map.fetch!(lineage_now.abundance_by_phase, phase_name)

        if count == prev do
          {:halt, {new_acc, count}}
        else
          {:cont, {new_acc, count}}
        end
      end)

    final_lineage = hd(final_state.lineages)
    final_count = Map.fetch!(final_lineage.abundance_by_phase, phase_name)

    # The fixed point must be non-negative (by the clamp invariant)
    assert final_count >= 0

    # Verify it is actually a fixed point: one more tick changes nothing
    {after_one_more, _} = Tick.tick(final_state)
    count_after = Map.fetch!(hd(after_one_more.lineages).abundance_by_phase, phase_name)

    assert count_after == final_count,
           "population has not converged: #{final_count} → #{count_after}"
  end

  # ---------------------------------------------------------------------------
  # Unit: stub steps return state unchanged

  test "step_metabolism returns state unchanged" do
    state = simple_state()
    assert Tick.step_metabolism(state) == state
  end

  test "step_expression updates growth_delta_by_lineage from genome" do
    # Phase 3: step_expression derives growth deltas from the genome.
    # A zero-kcat genome produces delta = 0 for every phase.
    state = zero_delta_state()
    new_state = Tick.step_expression(state)

    # growth_delta_by_lineage is now populated by step_expression
    lineage = hd(state.lineages)
    deltas = Map.fetch!(new_state.growth_delta_by_lineage, lineage.id)
    assert is_map(deltas)

    for {_phase, delta} <- deltas do
      assert delta == 0,
             "expected delta = 0 for zero-kcat genome, got #{delta}"
    end
  end

  test "step_hgt returns state unchanged" do
    state = simple_state()
    assert Tick.step_hgt(state) == state
  end

  test "step_pruning returns state unchanged" do
    state = simple_state()
    assert Tick.step_pruning(state) == state
  end

  # ---------------------------------------------------------------------------
  # Unit: step_cell_events clamps at zero

  test "step_cell_events clamps abundance at zero when delta is strongly negative" do
    phase_name = :surface
    initial_abundance = 10

    lineage =
      Lineage.new_founder(
        genome_fixture(),
        %{phase_name => initial_abundance},
        0
      )

    state =
      BiotopeState.new_from_opts(
        id: Arkea.UUID.v4(),
        archetype: :oligotrophic_lake,
        phases: [Phase.new(phase_name)],
        dilution_rate: 0.05,
        lineages: [lineage],
        growth_delta_by_lineage: %{lineage.id => %{phase_name => -1_000_000}}
      )

    new_state = Tick.step_cell_events(state)
    result_lineage = hd(new_state.lineages)
    assert Map.fetch!(result_lineage.abundance_by_phase, phase_name) == 0
  end

  # ---------------------------------------------------------------------------
  # Unit: step_environment uses per-phase dilution_rate

  test "step_environment applies per-phase dilution_rate" do
    phase_a = Phase.new(:surface, dilution_rate: 0.5)
    phase_b = Phase.new(:sediment, dilution_rate: 0.1)

    lineage =
      Lineage.new_founder(
        genome_fixture(),
        %{surface: 100, sediment: 100},
        0
      )

    state =
      BiotopeState.new_from_opts(
        id: Arkea.UUID.v4(),
        archetype: :eutrophic_pond,
        phases: [phase_a, phase_b],
        dilution_rate: 0.05,
        lineages: [lineage]
      )

    new_state = Tick.step_environment(state)
    result = hd(new_state.lineages)

    # floor(100 * 0.5) = 50
    assert Map.fetch!(result.abundance_by_phase, :surface) == 50
    # floor(100 * 0.9) = 90
    assert Map.fetch!(result.abundance_by_phase, :sediment) == 90
  end

  # ---------------------------------------------------------------------------
  # Phase 3 unit tests: step_expression → Phenotype → growth deltas

  test "step_expression produces non-nil deltas for all lineages with genome" do
    state = simple_state()
    new_state = Tick.step_expression(state)

    for lineage <- state.lineages do
      assert Map.has_key?(new_state.growth_delta_by_lineage, lineage.id),
             "lineage #{lineage.id} has no entry in growth_delta_by_lineage"

      deltas = Map.fetch!(new_state.growth_delta_by_lineage, lineage.id)
      assert is_map(deltas)
    end
  end

  test "genome with catalytic_site kcat ≈ 1.0 yields higher base_growth_rate than genome with none" do
    # A catalytic domain with all-max parameter_codons (value 19) has:
    # raw_sum ≈ 530, norm ≈ 1.0, kcat = 10.0 — but clamped to 1.0 as base_growth_rate.
    # A genome with only substrate_binding domains has base_growth_rate = 0.1 (default).
    #
    # Type index 1 = :catalytic_site → type_tag sum rem 11 = 1 → [0, 0, 1]
    # Type index 0 = :substrate_binding → type_tag [0, 0, 0]

    catalytic_domain = Domain.new([0, 0, 1], List.duplicate(19, 20))
    catalytic_gene = Gene.from_domains([catalytic_domain])
    genome_with_catalytic = Genome.new([catalytic_gene])
    phenotype_with_catalytic = Phenotype.from_genome(genome_with_catalytic)

    no_catalytic_domain = Domain.new([0, 0, 0], List.duplicate(0, 20))
    no_catalytic_gene = Gene.from_domains([no_catalytic_domain])
    genome_no_catalytic = Genome.new([no_catalytic_gene])
    phenotype_no_catalytic = Phenotype.from_genome(genome_no_catalytic)

    assert phenotype_with_catalytic.base_growth_rate >
             phenotype_no_catalytic.base_growth_rate,
           "genome with catalytic_site should have higher base_growth_rate than one without"
  end

  # ---------------------------------------------------------------------------
  # Property: step_expression produces non-nil deltas for all lineages

  property "step_expression produces deltas for all lineages with non-nil genome" do
    check all(state <- biotope_state()) do
      new_state = Tick.step_expression(state)

      for lineage <- state.lineages, lineage.genome != nil do
        assert Map.has_key?(new_state.growth_delta_by_lineage, lineage.id),
               "lineage #{lineage.id} has no entry in growth_delta_by_lineage"
      end
    end
  end

  # ---------------------------------------------------------------------------
  # Private helpers

  # A genome whose only domain is :catalytic_site with all-zero parameter_codons.
  # raw_sum = 0.0, norm = 0.0, kcat = 0.0 → base_growth_rate = 0.0, delta = 0.
  # Used to test pure-dilution monotonicity (no growth from the genome side).
  defp zero_kcat_genome do
    # type_tag [0,0,1] → sum=1 → rem(1,11)=1 → :catalytic_site (index 1)
    domain = Domain.new([0, 0, 1], List.duplicate(0, 20))
    gene = Gene.from_domains([domain])
    Genome.new([gene])
  end

  defp genome_fixture do
    domain = Domain.new([0, 0, 0], List.duplicate(0, 20))
    gene = Gene.from_domains([domain])
    Genome.new([gene])
  end

  defp simple_state do
    phase = Phase.new(:surface)

    lineage =
      Lineage.new_founder(
        genome_fixture(),
        %{surface: 100},
        0
      )

    BiotopeState.new_from_opts(
      id: Arkea.UUID.v4(),
      archetype: :oligotrophic_lake,
      phases: [phase],
      dilution_rate: 0.05,
      lineages: [lineage]
    )
  end

  defp zero_delta_state do
    phase = Phase.new(:surface)
    genome = zero_kcat_genome()

    lineage =
      Lineage.new_founder(
        genome,
        %{surface: 100},
        0
      )

    BiotopeState.new_from_opts(
      id: Arkea.UUID.v4(),
      archetype: :oligotrophic_lake,
      phases: [phase],
      dilution_rate: 0.05,
      lineages: [lineage]
    )
  end

  # StreamData generator: BiotopeState where every lineage carries the
  # zero-kcat genome → step_expression produces delta = 0 for every phase.
  # This lets us test pure-dilution monotonicity under Phase 3 step_expression.
  defp biotope_state_zero_delta do
    alias Arkea.Ecology.Biotope

    StreamData.bind(StreamData.member_of(Biotope.archetypes()), fn archetype ->
      StreamData.bind(Arkea.Generators.float_in(-1000.0, 1000.0), fn x ->
        StreamData.bind(Arkea.Generators.float_in(-1000.0, 1000.0), fn y ->
          biotope = Biotope.new(archetype, {x, y})
          phase_names = Enum.map(biotope.phases, & &1.name)
          genome = zero_kcat_genome()

          StreamData.bind(StreamData.integer(1..3), fn n ->
            StreamData.bind(
              StreamData.list_of(
                StreamData.bind(
                  StreamData.list_of(StreamData.integer(0..100_000), length: length(phase_names)),
                  fn counts ->
                    abundances = Enum.zip(phase_names, counts) |> Map.new()
                    StreamData.constant(Lineage.new_founder(genome, abundances, 0))
                  end
                ),
                length: n
              ),
              fn lineages ->
                state = BiotopeState.new(biotope, lineages)
                StreamData.constant(state)
              end
            )
          end)
        end)
      end)
    end)
  end

  # StreamData generator: BiotopeState where every lineage has abundance 0 in
  # all phases. `mutation_probability(0, _) = 0.0` so no fission occurs.
  # Used to test determinism and composability properties in Phase 4, where
  # fission introduces non-deterministic UUID generation.
  defp biotope_state_zero_abundance do
    alias Arkea.Ecology.Biotope

    StreamData.bind(StreamData.member_of(Biotope.archetypes()), fn archetype ->
      StreamData.bind(Arkea.Generators.float_in(-1000.0, 1000.0), fn x ->
        StreamData.bind(Arkea.Generators.float_in(-1000.0, 1000.0), fn y ->
          biotope = Biotope.new(archetype, {x, y})
          phase_names = Enum.map(biotope.phases, & &1.name)
          genome = zero_kcat_genome()

          StreamData.bind(StreamData.integer(1..3), fn n ->
            lineages =
              Enum.map(1..n, fn _ ->
                abundances = Map.new(phase_names, fn name -> {name, 0} end)
                Lineage.new_founder(genome, abundances, 0)
              end)

            state = BiotopeState.new(biotope, lineages)
            StreamData.constant(state)
          end)
        end)
      end)
    end)
  end
end
